#!/bin/bash

#To get the logged in user information
USER=$(whoami)

#System Information

#To generate hostname
HOSTNAME=$(hostname)

#To get the OS Information
OS=$(source /etc/os-release && echo $NAME && echo $VERSION)

#To get the system uptime
UPTIME=$(uptime -p)

#To get the cpu processor make and model information
CPU_INFORMATION=$(cat /proc/cpuinfo | grep "model name" | head -n 1 | sed 's/.*: //')


#The output report directly to the terminal
cat <<EOF


System Report generated by $USER,$(date)

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
cpu: $CPU_INFORMATION
Speed: $CPU_SPEED
Ram: $RAM
Disk(s):
$DISKS
Video: $VIDEO_CARD



EOF
