#!/bin/bash

#To get the logged in user information
USER=$(whoami)

#System Information

#To generate hostname
HOSTNAME=$(hostname)

#To get the OS Information
OS=$(source /etc/os-release && echo $NAME && echo $VERSION)

#To get the system uptime
UPTIME=$(uptime -p)

#To get the cpu processor make and model information
CPU_INFORMATION=$(cat /proc/cpuinfo | grep "model name" | head -n 1 | sed 's/.*: //')

#To get the size of installed RAM
RAM=$(grep MemTotal /proc/meminfo | awk '{printf "%.1fGi\n", $2/1024/1024}')

#To get the make and model and size for all installed disks
DISKS=$(sudo lshw -class disk -short | awk '/disk/ {printf "Make: %s Model: %s Size: %s\n", $3, $4, $5}')

#Getting the make and model of video card
VIDEO_CARD=$(lspci | grep -i vga | awk '{$1="";$2=""; print $0}')

#The output report directly to the terminal
cat <<EOF


System Report generated by $USER,$(date)

System Information
------------------
Hostname: $HOSTNAME
      OS: $OS
  Uptime: $UPTIME

Hardware Information
--------------------
    Cpu: $CPU_INFORMATION
    Ram: $RAM
Disk(s):$DISKS
Video: $VIDEO_CARD



EOF
